"""Module 10 — professional PDF security reports (ReportLab)."""
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)

from constants import RECOMMENDATIONS, RESULT_MESSAGES

RISK_COLORS = {"NONE": colors.HexColor("#1f9d55"), "LOW": colors.HexColor("#d4a017"),
               "MEDIUM": colors.HexColor("#dd6b20"), "HIGH": colors.HexColor("#e53e3e"),
               "CRITICAL": colors.HexColor("#9b1c1c"), "UNKNOWN": colors.HexColor("#718096")}


def build_scan_pdf(record, user) -> bytes:
    """Render a one-scan security report. Returns PDF bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=20 * mm, rightMargin=20 * mm,
                            topMargin=20 * mm, bottomMargin=20 * mm,
                            title=f"Malware Scan Report {record.scan_uuid}")
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Title"], fontSize=20, textColor=colors.HexColor("#0f2743"))
    h2 = ParagraphStyle("h2", parent=styles["Heading2"], textColor=colors.HexColor("#0f2743"))
    body = styles["BodyText"]
    small = ParagraphStyle("small", parent=body, fontSize=8, textColor=colors.grey)

    story = [Paragraph("Malware Detection Using AI — Security Scan Report", h1), Spacer(1, 6 * mm)]

    conf = f"{record.confidence:.2%}" if record.confidence is not None else "Not available"
    rows = [
        ["Report title", "File Scan Report"],
        ["Scan ID", record.scan_uuid],
        ["Requested by", f"{user.name} <{user.email}>"],
        ["File name", record.file_name],
        ["File type", record.file_type],
        ["File size", f"{record.file_size:,} bytes"],
        ["SHA-256", record.sha256 or "n/a"],
        ["Scan timestamp (UTC)", record.created_at.strftime("%Y-%m-%d %H:%M:%S")],
        ["Detection result", record.detection_result],
        ["Risk level", record.risk_level],
        ["Confidence score", conf],
        ["Scan status", record.status],
        ["Source", record.source.upper()],
    ]
    table = Table(rows, colWidths=[45 * mm, 125 * mm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2f7")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cbd5e0")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story += [table, Spacer(1, 6 * mm)]

    story.append(Paragraph("Detection details", h2))
    story.append(Paragraph(RESULT_MESSAGES.get(record.detection_result, ""), body))
    story.append(Spacer(1, 2 * mm))
    for line in (record.detail or "").splitlines():
        story.append(Paragraph(line.replace("&", "&amp;").replace("<", "&lt;"), body))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Security recommendation", h2))
    story.append(Paragraph(RECOMMENDATIONS.get(record.detection_result, ""), body))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Summary", h2))
    story.append(Paragraph(
        f"The file <b>{record.file_name}</b> was analysed by the configured machine-learning "
        f"model and classified as <b>{record.detection_result}</b> "
        f"(risk level <b>{record.risk_level}</b>, confidence {conf}). "
        "This report reflects the model's assessment at the time of scanning and is not a "
        "guarantee that a file is safe or malicious.", body))
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(
        "Generated by Malware Detection Using AI. Automated analysis — verify critical "
        "findings with a qualified security analyst.", small))

    doc.build(story)
    return buf.getvalue()
